const CHANNEL = "moyu-storage-v1";

// The iframe may execute before React installs the parent listener. Repeat the
// same idempotent request briefly so the first load never waits for a timeout.
export const appStorageBridge = `<script>(function(){var seq=0,pending=new Map();function legacy(action,key,value){return new Promise(function(resolve,reject){var id=++seq,msg={channel:'${CHANNEL}',id:id,action:action,key:key,value:value};function send(){parent.postMessage(msg,'*')}var retry=setInterval(send,100),timeout=setTimeout(function(){var p=pending.get(id);if(!p)return;pending.delete(id);clearInterval(retry);reject(new Error('存档请求超时'))},5000);pending.set(id,{resolve:resolve,reject:reject,retry:retry,timeout:timeout});send()})}var sdkPending=new Map();function sdk(method,params){return new Promise(function(resolve,reject){var requestId=(crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(36).slice(2));var timeout=setTimeout(function(){sdkPending.delete(requestId);var e=new Error('SDK 请求超时');e.code='SDK_TIMEOUT';reject(e)},10000);sdkPending.set(requestId,{resolve:resolve,reject:reject,timeout:timeout});parent.postMessage({source:'moyu-app',version:'1.0',type:'MOYU_SDK_REQUEST',requestId:requestId,method:method,params:params||{}},'*')})}window.addEventListener('message',function(e){var m=e.data;if(m&&m.channel==='${CHANNEL}'&&m.response){var p=pending.get(m.id);if(!p)return;pending.delete(m.id);clearInterval(p.retry);clearTimeout(p.timeout);m.ok?p.resolve(m.value):p.reject(new Error(m.error||'存档失败'));return}if(!m||m.source!=='moyu-platform'||m.type!=='MOYU_SDK_RESPONSE')return;var q=sdkPending.get(m.requestId);if(!q)return;sdkPending.delete(m.requestId);clearTimeout(q.timeout);if(m.success)q.resolve(m.data);else{var er=new Error(m.error&&m.error.message||'SDK 请求失败');er.code=m.error&&m.error.code||'INTERNAL_ERROR';q.reject(er)}});window.MoyuSDK={ready:function(){return Promise.resolve()},getCurrentUser:function(){return sdk('user.getCurrent')},getAppInfo:function(){return sdk('app.getInfo')},get:function(k){return sdk('storage.get',{key:k})},set:function(k,v){return sdk('storage.set',{key:k,value:v})},remove:function(k){return sdk('storage.remove',{key:k})}};window.MoyuStorage={set:function(k,v){return legacy('set',k,v)},get:function(k){return legacy('get',k)},remove:function(k){return legacy('remove',k)},clear:function(){return legacy('clear')},keys:function(){return legacy('keys')}};window.dispatchEvent(new Event('moyu-sdk-ready'));window.dispatchEvent(new Event('moyu-storage-ready'))})();<\/script>`;

export function injectAppStorageBridge(html:string){
  if(html.includes(CHANNEL))return html;
  const head=/<\/head\s*>/i;
  return head.test(html)?html.replace(head,appStorageBridge+"</head>"):appStorageBridge+html;
}
